package com.arpitkatiyarprojects.countrypicker.utils

import android.content.Context
import android.telephony.TelephonyManager
import com.arpitkatiyarprojects.countrypicker.R
import com.arpitkatiyarprojects.countrypicker.models.CountryDetails

internal object FunctionHelper {


    /**
     * Searches for countries in the list of [CountryDetails] based on the specified search string.
     *
     * @param searchStr The search string to match against country names, phone number codes, and country codes.
     * @return A list of [CountryDetails] matching the search criteria.
     */
    fun List<CountryDetails>.searchForCountry(searchStr: String): List<CountryDetails> {
        return filter {
            it.countryName.contains(searchStr, ignoreCase = true)
                    || it.countryPhoneNumberCode.contains(searchStr, ignoreCase = true)
                    || it.countryCode.contains(searchStr, ignoreCase = true)
        }
    }


    /**
     * Retrieves the default selected country based on the provided parameters.
     *
     * @param context The context used for retrieving default country code if countryCode is null.
     * @param countryCode The country code of the selected country.
     * @param countriesList The list of [CountryDetails] containing country information.
     * @return The default selected [CountryDetails].
     */
    fun getDefaultSelectedCountry(
        context: Context,
        countryCode: String?,
        countriesList: List<CountryDetails>
    ): CountryDetails {
        return try {
            if (!countryCode.isNullOrBlank()) {
                getCountryForCountryCode(countriesList, countryCode)
            } else {
                getDefaultCountryCode(context, countriesList)
            }
        } catch (exception: Exception) {
            LoggerHelper.logError(exception)
            countriesList[0]
        }
    }


    /**
     * Retrieves the country details for the specified country code.
     *
     * @param countriesList The list of [CountryDetails] containing country information.
     * @param countryCode The country code of the desired country.
     * @return The [CountryDetails] corresponding to the provided country code.
     * @throws NoSuchElementException if no country with the specified country code is found in the list.
     */
    private fun getCountryForCountryCode(
        countriesList: List<CountryDetails>,
        countryCode: String
    ): CountryDetails {
        return countriesList.single { it.countryCode == countryCode }
    }


    /**
     * Retrieves the default country details based on the current locale.
     *
     * @param context The context used for accessing system services.
     * @param countriesList The list of [CountryDetails] containing country information.
     * @return The default country details based on the current locale.
     */
    private fun getDefaultCountryCode(
        context: Context,
        countriesList: List<CountryDetails>
    ): CountryDetails {
        val localeCode: TelephonyManager =
            context.getSystemService(Context.TELEPHONY_SERVICE) as TelephonyManager
        val countryCode = localeCode.networkCountryIso
        return getCountryForCountryCode(countriesList, countryCode.lowercase())
    }


    /**
     * Retrieves the details of all countries.
     *
     * @param context The context used for accessing country name from string file to provide multilanguage feature.
     * @return The list of [CountryDetails] containing details of all countries.
     */
    fun getAllCountries(context: Context): List<CountryDetails> = listOf(
        CountryDetails(
            countryCode = "ad",
            "+376",
            context.getString(R.string.andorra),
            R.drawable.ad,
        ),
        CountryDetails(
            countryCode = "ae",
            "+971",
            context.getString(R.string.united_arab_emirates_uae),
            R.drawable.ae,
        ),
        CountryDetails(
            countryCode = "af",
            "+93",
            context.getString(R.string.afghanistan),
            R.drawable.af,
        ),
        CountryDetails(
            countryCode = "ag",
            "+1",
            context.getString(R.string.antigua_and_barbuda),
            R.drawable.ag,
        ),
        CountryDetails(
            "ai",
            "+1",
            context.getString(R.string.anguilla),
            R.drawable.ai,
        ),
        CountryDetails(
            "al",
            "+355",
            context.getString(R.string.albania),
            R.drawable.al,
        ),
        CountryDetails(
            "am",
            "+374",
            context.getString(R.string.armenia),
            R.drawable.am,
        ),
        CountryDetails(
            "ao",
            "+244",
            context.getString(R.string.angola),
            R.drawable.ao,
        ),
        CountryDetails(
            "aq",
            "+672",
            context.getString(R.string.antarctica),
            R.drawable.aq,
        ),
        CountryDetails(
            "ar",
            "+54",
            context.getString(R.string.argentina),
            R.drawable.ar,
        ),
        CountryDetails(
            "as",
            "+1",
            context.getString(R.string.american_samoa),
            R.drawable.`as`
        ),
        CountryDetails(
            "at",
            "+43",
            context.getString(R.string.austria),
            R.drawable.at,
        ),
        CountryDetails(
            "au",
            "+61",
            context.getString(R.string.australia),
            R.drawable.au,
        ),
        CountryDetails(
            "aw",
            "+297",
            context.getString(R.string.aruba),
            R.drawable.aw,
        ),
        CountryDetails(
            "ax",
            "+358",
            context.getString(R.string.land_islands),
            R.drawable.ax
        ),
        CountryDetails(
            "az",
            "+994",
            context.getString(R.string.azerbaijan),
            R.drawable.az
        ),
        CountryDetails(
            "ba",
            "+387",
            context.getString(R.string.bosnia_and_herzegovina),
            R.drawable.ba
        ),
        CountryDetails(
            "bb",
            "+1",
            context.getString(R.string.barbados),
            R.drawable.bb
        ),
        CountryDetails(
            "bd",
            "+880",
            context.getString(R.string.bangladesh),
            R.drawable.bd
        ),
        CountryDetails(
            "be",
            "+32",
            context.getString(R.string.belgium),
            R.drawable.be
        ),
        CountryDetails(
            "bf",
            "+226",
            context.getString(R.string.burkina_faso),
            R.drawable.bf
        ),
        CountryDetails(
            "bg",
            "+359",
            context.getString(R.string.bulgaria),
            R.drawable.bg
        ),
        CountryDetails(
            "bh",
            "+973",
            context.getString(R.string.bahrain),
            R.drawable.bh
        ),
        CountryDetails(
            "bi",
            "+257",
            context.getString(R.string.burundi),
            R.drawable.bi
        ),
        CountryDetails(
            "bj",
            "+229",
            context.getString(R.string.benin),
            R.drawable.bj
        ),
        CountryDetails(
            "bl",
            "+590",
            context.getString(R.string.saint_barth_lemy),
            R.drawable.bl
        ),
        CountryDetails(
            "bm",
            "+1",
            context.getString(R.string.bermuda),
            R.drawable.bm
        ),
        CountryDetails(
            "bn",
            "+673",
            context.getString(R.string.brunei_darussalam),
            R.drawable.bn
        ),
        CountryDetails(
            "bo",
            "+591",
            context.getString(R.string.bolivia_plurinational_state_of),
            R.drawable.bo
        ),
        CountryDetails(
            "br",
            "+55",
            context.getString(R.string.brazil),
            R.drawable.br
        ),
        CountryDetails(
            "bs",
            "+1",
            context.getString(R.string.bahamas),
            R.drawable.bs
        ),
        CountryDetails(
            "bt",
            "+975",
            context.getString(R.string.bhutan),
            R.drawable.bt
        ),
        CountryDetails(
            "bw",
            "+267",
            context.getString(R.string.botswana),
            R.drawable.bw
        ),
        CountryDetails(
            "by",
            "+375",
            context.getString(R.string.belarus),
            R.drawable.by
        ),
        CountryDetails(
            "bz",
            "+501",
            context.getString(R.string.belize),
            R.drawable.bz
        ),
        CountryDetails(
            "ca",
            "+1",
            context.getString(R.string.canada),
            R.drawable.ca
        ),
        CountryDetails(
            "cc",
            "+61",
            context.getString(R.string.cocos_keeling_islands),
            R.drawable.cc
        ),
        CountryDetails(
            "cd",
            "+243",
            context.getString(R.string.congo_the_democratic_republic_of_the),
            R.drawable.cd
        ),
        CountryDetails(
            "cf",
            "+236",
            context.getString(R.string.central_african_republic),
            R.drawable.cf
        ),
        CountryDetails(
            "cg",
            "+242",
            context.getString(R.string.congo),
            R.drawable.cg
        ),
        CountryDetails(
            "ch",
            "+41",
            context.getString(R.string.switzerland),
            R.drawable.ch
        ),
        CountryDetails(
            "ci",
            "+225",
            context.getString(R.string.c_te_d_ivoire),
            R.drawable.ci
        ),
        CountryDetails(
            "ck",
            "+682",
            context.getString(R.string.cook_islands),
            R.drawable.ck
        ),
        CountryDetails(
            "cl",
            "+56",
            context.getString(R.string.chile),
            R.drawable.cl
        ),
        CountryDetails(
            "cm",
            "+237",
            context.getString(R.string.cameroon),
            R.drawable.cm
        ),
        CountryDetails(
            "cn",
            "+86",
            context.getString(R.string.china),
            R.drawable.cn
        ),
        CountryDetails(
            "co",
            "+57",
            context.getString(R.string.colombia),
            R.drawable.co
        ),
        CountryDetails(
            "cr",
            "+506",
            context.getString(R.string.costa_rica),
            R.drawable.cr
        ),
        CountryDetails(
            "cu",
            "+53",
            context.getString(R.string.cuba),
            R.drawable.cu
        ),
        CountryDetails(
            "cv",
            "+238",
            context.getString(R.string.cape_verde),
            R.drawable.cv
        ),
        CountryDetails(
            "cw",
            "+599",
            context.getString(R.string.cura_ao),
            R.drawable.cw
        ),
        CountryDetails(
            "cx",
            "+61",
            context.getString(R.string.christmas_island),
            R.drawable.cx
        ),
        CountryDetails(
            "cy",
            "+357",
            context.getString(R.string.cyprus),
            R.drawable.cy
        ),
        CountryDetails(
            "cz",
            "+420",
            context.getString(R.string.czech_republic),
            R.drawable.cz
        ),
        CountryDetails(
            "de",
            "+49",
            context.getString(R.string.germany),
            R.drawable.de
        ),
        CountryDetails(
            "dj",
            "+253",
            context.getString(R.string.djibouti),
            R.drawable.dj
        ),
        CountryDetails(
            "dk",
            "+45",
            context.getString(R.string.denmark),
            R.drawable.dk
        ),
        CountryDetails(
            "dm",
            "+1",
            context.getString(R.string.dominica),
            R.drawable.dm
        ),
        CountryDetails(
            "do",
            "+1",
            context.getString(R.string.dominican_republic),
            R.drawable.ic_do
        ),
        CountryDetails(
            "dz",
            "+213",
            context.getString(R.string.algeria),
            R.drawable.dz
        ),
        CountryDetails(
            "ec",
            "+593",
            context.getString(R.string.ecuador),
            R.drawable.ec
        ),
        CountryDetails(
            "ee",
            "+372",
            context.getString(R.string.estonia),
            R.drawable.ee
        ),
        CountryDetails(
            "eg",
            "+20",
            context.getString(R.string.egypt),
            R.drawable.eg
        ),
        CountryDetails(
            "er",
            "+291",
            context.getString(R.string.eritrea),
            R.drawable.er
        ),
        CountryDetails(
            "es",
            "+34",
            context.getString(R.string.spain),
            R.drawable.es
        ),
        CountryDetails(
            "et",
            "+251",
            context.getString(R.string.ethiopia),
            R.drawable.et
        ),
        CountryDetails(
            "fi",
            "+358",
            context.getString(R.string.finland),
            R.drawable.fi
        ),
        CountryDetails(
            "fj",
            "+679",
            context.getString(R.string.fiji),
            R.drawable.fj
        ),
        CountryDetails(
            "fk",
            "+500",
            context.getString(R.string.falkland_islands_malvinas),
            R.drawable.fk
        ),
        CountryDetails(
            "fm",
            "+691",
            context.getString(R.string.micronesia_federated_states_of),
            R.drawable.fm
        ),
        CountryDetails(
            "fo",
            "+298",
            context.getString(R.string.faroe_islands),
            R.drawable.fo
        ),
        CountryDetails(
            "fr",
            "+33",
            context.getString(R.string.france),
            R.drawable.fr
        ),
        CountryDetails(
            "ga",
            "+241",
            context.getString(R.string.gabon),
            R.drawable.ga
        ),
        CountryDetails(
            "gb",
            "+44",
            context.getString(R.string.united_kingdom),
            R.drawable.gb
        ),
        CountryDetails(
            "gd",
            "+1",
            context.getString(R.string.grenada),
            R.drawable.gd
        ),
        CountryDetails(
            "ge",
            "+995",
            context.getString(R.string.georgia),
            R.drawable.ge
        ),
        CountryDetails(
            "gf",
            "+594",
            context.getString(R.string.french_guyana),
            R.drawable.gf
        ),
        CountryDetails(
            "gh",
            "+233",
            context.getString(R.string.ghana),
            R.drawable.gh
        ),
        CountryDetails(
            "gi",
            "+350",
            context.getString(R.string.gibraltar),
            R.drawable.gi
        ),
        CountryDetails(
            "gl",
            "+299",
            context.getString(R.string.greenland),
            R.drawable.gl
        ),
        CountryDetails(
            "gm",
            "+220",
            "Gambia",
            R.drawable.gm
        ),
        CountryDetails(
            "gn",
            "+224",
            context.getString(R.string.guinea),
            R.drawable.gn
        ),
        CountryDetails(
            "gp",
            "+450",
            context.getString(R.string.guadeloupe),
            R.drawable.gp
        ),
        CountryDetails(
            "gq",
            "+240",
            context.getString(R.string.equatorial_guinea),
            R.drawable.gq
        ),
        CountryDetails(
            "gr",
            "+30",
            context.getString(R.string.greece),
            R.drawable.gr
        ),
        CountryDetails(
            "gt",
            "+502",
            context.getString(R.string.guatemala),
            R.drawable.gt
        ),
        CountryDetails(
            "gu",
            "+1",
            context.getString(R.string.guam),
            R.drawable.gu
        ),
        CountryDetails(
            "gw",
            "+245",
            context.getString(R.string.guinea_bissau),
            R.drawable.gw
        ),
        CountryDetails(
            "gy",
            "+592",
            context.getString(R.string.guyana),
            R.drawable.gy
        ),
        CountryDetails(
            "hk",
            "+852",
            context.getString(R.string.hong_kong),
            R.drawable.hk
        ),
        CountryDetails(
            "hn",
            "+504",
            context.getString(R.string.honduras),
            R.drawable.hn
        ),
        CountryDetails(
            "hr",
            "+385",
            context.getString(R.string.croatia),
            R.drawable.hr
        ),
        CountryDetails(
            "ht",
            "+509",
            context.getString(R.string.haiti),
            R.drawable.ht
        ),
        CountryDetails(
            "hu",
            "+36",
            context.getString(R.string.hungary),
            R.drawable.hu
        ),
        CountryDetails(
            "id",
            "+62",
            context.getString(R.string.indonesia),
            R.drawable.id
        ),
        CountryDetails(
            "ie",
            "+353",
            context.getString(R.string.ireland),
            R.drawable.ie
        ),
        CountryDetails(
            "il",
            "+972",
            context.getString(R.string.israel),
            R.drawable.il
        ),
        CountryDetails(
            "im",
            "+44",
            context.getString(R.string.isle_of_man),
            R.drawable.im
        ),
        CountryDetails(
            "is",
            "+354",
            context.getString(R.string.iceland),
            R.drawable.`is`
        ),
        CountryDetails(
            "in",
            "+91",
            context.getString(R.string.india),
            R.drawable.`in`
        ),
        CountryDetails(
            "io",
            "+246",
            context.getString(R.string.british_indian_ocean_territory),
            R.drawable.io
        ),
        CountryDetails(
            "iq",
            "+964",
            context.getString(R.string.iraq),
            R.drawable.iq
        ),
        CountryDetails(
            "ir",
            "+98",
            context.getString(R.string.iran_islamic_republic_of),
            R.drawable.ir
        ),
        CountryDetails(
            "it",
            "+39",
            context.getString(R.string.italy),
            R.drawable.it
        ),
        CountryDetails(
            "je",
            "+44",
            context.getString(R.string.jersey),
            R.drawable.je
        ),
        CountryDetails(
            "jm",
            "+1",
            context.getString(R.string.jamaica),
            R.drawable.jm
        ),
        CountryDetails(
            "jo",
            "+962",
            context.getString(R.string.jordan),
            R.drawable.jo
        ),
        CountryDetails(
            "jp",
            "+81",
            context.getString(R.string.japan),
            R.drawable.jp
        ),
        CountryDetails(
            "ke",
            "+254",
            context.getString(R.string.kenya),
            R.drawable.ke
        ),
        CountryDetails(
            "kg",
            "+996",
            context.getString(R.string.kyrgyzstan),
            R.drawable.kg
        ),
        CountryDetails(
            "kh",
            "+855",
            context.getString(R.string.cambodia),
            R.drawable.kh
        ),
        CountryDetails(
            "ki",
            "+686",
            context.getString(R.string.kiribati),
            R.drawable.ki
        ),
        CountryDetails(
            "km",
            "+269",
            context.getString(R.string.comoros),
            R.drawable.km
        ),
        CountryDetails(
            "kn",
            "+1",
            context.getString(R.string.saint_kitts_and_nevis),
            R.drawable.kn
        ),
        CountryDetails(
            "kp",
            "+850",
            context.getString(R.string.north_korea),
            R.drawable.kp
        ),
        CountryDetails(
            "kr",
            "+82",
            context.getString(R.string.south_korea),
            R.drawable.kr
        ),
        CountryDetails(
            "kw",
            "+965",
            context.getString(R.string.kuwait),
            R.drawable.kw
        ),
        CountryDetails(
            "ky",
            "+1",
            context.getString(R.string.cayman_islands),
            R.drawable.ky
        ),
        CountryDetails(
            "kz",
            "+7",
            context.getString(R.string.kazakhstan),
            R.drawable.kz
        ),
        CountryDetails(
            "la",
            "+856",
            context.getString(R.string.lao_people_s_democratic_republic),
            R.drawable.la
        ),
        CountryDetails(
            "lb",
            "+961",
            context.getString(R.string.lebanon),
            R.drawable.lb
        ),
        CountryDetails(
            "lc",
            "+1",
            context.getString(R.string.saint_lucia),
            R.drawable.lc
        ),
        CountryDetails(
            "li",
            "+423",
            context.getString(R.string.liechtenstein),
            R.drawable.li
        ),
        CountryDetails(
            "lk",
            "+94",
            context.getString(R.string.sri_lanka),
            R.drawable.lk
        ),
        CountryDetails(
            "lr",
            "+231",
            context.getString(R.string.liberia),
            R.drawable.lr
        ),
        CountryDetails(
            "ls",
            "+266",
            context.getString(R.string.lesotho),
            R.drawable.ls
        ),
        CountryDetails(
            "lt",
            "+370",
            context.getString(R.string.lithuania),
            R.drawable.lt
        ),
        CountryDetails(
            "lu",
            "+352",
            context.getString(R.string.luxembourg),
            R.drawable.lu
        ),
        CountryDetails(
            "lv",
            "+371",
            context.getString(R.string.latvia),
            R.drawable.lv
        ),
        CountryDetails(
            "ly",
            "+218",
            context.getString(R.string.libya),
            R.drawable.ly
        ),
        CountryDetails(
            "ma",
            "+212",
            context.getString(R.string.morocco),
            R.drawable.ma
        ),
        CountryDetails(
            "mc",
            "+377",
            context.getString(R.string.monaco),
            R.drawable.mc
        ),
        CountryDetails(
            "md",
            "+373",
            context.getString(R.string.moldova_republic_of),
            R.drawable.md
        ),
        CountryDetails(
            "me",
            "+382",
            context.getString(R.string.montenegro),
            R.drawable.me
        ),
        CountryDetails(
            "mf",
            "+590",
            context.getString(R.string.saint_martin),
            R.drawable.mf
        ),
        CountryDetails(
            "mg",
            "+261",
            context.getString(R.string.madagascar),
            R.drawable.mg
        ),
        CountryDetails(
            "mh",
            "+692",
            context.getString(R.string.marshall_islands),
            R.drawable.mh
        ),
        CountryDetails(
            "mk",
            "+389",
            context.getString(R.string.macedonia_fyrom),
            R.drawable.mk
        ),
        CountryDetails(
            "ml",
            "+223",
            context.getString(R.string.mali),
            R.drawable.ml
        ),
        CountryDetails(
            "mm",
            "+95",
            context.getString(R.string.myanmar),
            R.drawable.mm
        ),
        CountryDetails(
            "mn",
            "+976",
            context.getString(R.string.mongolia),
            R.drawable.mn
        ),
        CountryDetails(
            "mo",
            "+853",
            context.getString(R.string.macau),
            R.drawable.mo
        ),
        CountryDetails(
            "mp",
            "+1",
            context.getString(R.string.northern_mariana_islands),
            R.drawable.mp
        ),
        CountryDetails(
            "mq",
            "+596",
            context.getString(R.string.martinique),
            R.drawable.mq
        ),
        CountryDetails(
            "mr",
            "+222",
            context.getString(R.string.mauritania),
            R.drawable.mr
        ),
        CountryDetails(
            "ms",
            "+1",
            context.getString(R.string.montserrat),
            R.drawable.ms
        ),
        CountryDetails(
            "mt",
            "+356",
            context.getString(R.string.malta),
            R.drawable.mt
        ),
        CountryDetails(
            "mu",
            "+230",
            context.getString(R.string.mauritius),
            R.drawable.mu
        ),
        CountryDetails(
            "mv",
            "+960",
            context.getString(R.string.maldives),
            R.drawable.mv
        ),
        CountryDetails(
            "mw",
            "+265",
            context.getString(R.string.malawi),
            R.drawable.mw
        ),
        CountryDetails(
            "mx",
            "+52",
            context.getString(R.string.mexico),
            R.drawable.mx
        ),
        CountryDetails(
            "my",
            "+60",
            context.getString(R.string.malaysia),
            R.drawable.my
        ),
        CountryDetails(
            "mz",
            "+258",
            context.getString(R.string.mozambique),
            R.drawable.mz
        ),
        CountryDetails(
            "na",
            "+264",
            context.getString(R.string.namibia),
            R.drawable.na
        ),
        CountryDetails(
            "nc",
            "+687",
            context.getString(R.string.new_caledonia),
            R.drawable.nc
        ),
        CountryDetails(
            "ne",
            "+227",
            context.getString(R.string.niger),
            R.drawable.ne
        ),
        CountryDetails(
            "nf",
            "+672",
            context.getString(R.string.norfolk_islands),
            R.drawable.nf
        ),
        CountryDetails(
            "ng",
            "+234",
            context.getString(R.string.nigeria),
            R.drawable.ng
        ),
        CountryDetails(
            "ni",
            "+505",
            context.getString(R.string.nicaragua),
            R.drawable.ni
        ),
        CountryDetails(
            "nl",
            "+31",
            context.getString(R.string.netherlands),
            R.drawable.nl
        ),
        CountryDetails(
            "no",
            "+47",
            context.getString(R.string.norway),
            R.drawable.no
        ),
        CountryDetails(
            "np",
            "+977",
            context.getString(R.string.nepal),
            R.drawable.np
        ),
        CountryDetails(
            "nr",
            "+674",
            context.getString(R.string.nauru),
            R.drawable.nr
        ),
        CountryDetails(
            "nu",
            "+683",
            context.getString(R.string.niue),
            R.drawable.nu
        ),
        CountryDetails(
            "nz",
            "+64",
            context.getString(R.string.new_zealand),
            R.drawable.nz
        ),
        CountryDetails(
            "om",
            "+968",
            context.getString(R.string.oman),
            R.drawable.om
        ),
        CountryDetails(
            "pa",
            "+507",
            context.getString(R.string.panama),
            R.drawable.pa
        ),
        CountryDetails(
            "pe",
            "+51",
            context.getString(R.string.peru),
            R.drawable.pe
        ),
        CountryDetails(
            "pf",
            "+689",
            context.getString(R.string.french_polynesia),
            R.drawable.pf
        ),
        CountryDetails(
            "pg",
            "+675",
            context.getString(R.string.papua_new_guinea),
            R.drawable.pg
        ),
        CountryDetails(
            "ph",
            "+63",
            context.getString(R.string.philippines),
            R.drawable.ph
        ),
        CountryDetails(
            "pk",
            "+92",
            context.getString(R.string.pakistan),
            R.drawable.pk
        ),
        CountryDetails(
            "pl",
            "+48",
            context.getString(R.string.poland),
            R.drawable.pl
        ),
        CountryDetails(
            "pm",
            "+508",
            context.getString(R.string.saint_pierre_and_miquelon),
            R.drawable.pm
        ),
        CountryDetails(
            "pn",
            "+870",
            context.getString(R.string.pitcairn_islands),
            R.drawable.pn
        ),
        CountryDetails(
            "pr",
            "+1",
            context.getString(R.string.puerto_rico),
            R.drawable.pr
        ),
        CountryDetails(
            "ps",
            "+970",
            context.getString(R.string.palestine),
            R.drawable.ps
        ),
        CountryDetails(
            "pt",
            "+351",
            context.getString(R.string.portugal),
            R.drawable.pt
        ),
        CountryDetails(
            "pw",
            "+680",
            context.getString(R.string.palau),
            R.drawable.pw
        ),
        CountryDetails(
            "py",
            "+595",
            context.getString(R.string.paraguay),
            R.drawable.py
        ),
        CountryDetails(
            "qa",
            "+974",
            context.getString(R.string.qatar),
            R.drawable.qa
        ),
        CountryDetails(
            "re",
            "+262",
            context.getString(R.string.r_union),
            R.drawable.re
        ),
        CountryDetails(
            "ro",
            "+40",
            context.getString(R.string.romania),
            R.drawable.ro
        ),
        CountryDetails(
            "rs",
            "+381",
            context.getString(R.string.serbia),
            R.drawable.rs
        ),
        CountryDetails(
            "ru",
            "+7",
            context.getString(R.string.russian_federation),
            R.drawable.ru
        ),
        CountryDetails(
            "rw",
            "+250",
            context.getString(R.string.rwanda),
            R.drawable.rw
        ),
        CountryDetails(
            "sa",
            "+966",
            context.getString(R.string.saudi_arabia),
            R.drawable.sa
        ),
        CountryDetails(
            "sb",
            "+677",
            context.getString(R.string.solomon_islands),
            R.drawable.sb
        ),
        CountryDetails(
            "sc",
            "+248",
            context.getString(R.string.seychelles),
            R.drawable.sc
        ),
        CountryDetails(
            "sd",
            "+249",
            context.getString(R.string.sudan),
            R.drawable.sd
        ),
        CountryDetails(
            "se",
            "+46",
            context.getString(R.string.sweden),
            R.drawable.se
        ),
        CountryDetails(
            "sg",
            "+65",
            context.getString(R.string.singapore),
            R.drawable.sg
        ),
        CountryDetails(
            "sh",
            "+290",
            context.getString(R.string.saint_helena_ascension_and_tristan_da_cunha),
            R.drawable.sh
        ),
        CountryDetails(
            "si",
            "+386",
            context.getString(R.string.slovenia),
            R.drawable.si
        ),
        CountryDetails(
            "sk",
            "+421",
            context.getString(R.string.slovakia),
            R.drawable.sk
        ),
        CountryDetails(
            "sl",
            "+232",
            context.getString(R.string.sierra_leone),
            R.drawable.sl
        ),
        CountryDetails(
            "sm",
            "+378",
            context.getString(R.string.san_marino),
            R.drawable.sm
        ),
        CountryDetails(
            "sn",
            "+221",
            context.getString(R.string.senegal),
            R.drawable.sn
        ),
        CountryDetails(
            "so",
            "+252",
            context.getString(R.string.somalia),
            R.drawable.so
        ),
        CountryDetails(
            "sr",
            "+597",
            context.getString(R.string.suriname),
            R.drawable.sr
        ),
        CountryDetails(
            "ss",
            "+211",
            context.getString(R.string.south_sudan),
            R.drawable.ss
        ),
        CountryDetails(
            "st",
            "+239",
            context.getString(R.string.sao_tome_and_principe),
            R.drawable.st
        ),
        CountryDetails(
            "sv",
            "+503",
            context.getString(R.string.el_salvador),
            R.drawable.sv
        ),
        CountryDetails(
            "sx",
            "+1",
            context.getString(R.string.sint_maarten),
            R.drawable.sx
        ),
        CountryDetails(
            "sy",
            "+963",
            context.getString(R.string.syrian_arab_republic),
            R.drawable.sy
        ),
        CountryDetails(
            "sz",
            "+268",
            context.getString(R.string.swaziland),
            R.drawable.sz
        ),
        CountryDetails(
            "tc",
            "+1",
            context.getString(R.string.turks_and_caicos_islands),
            R.drawable.tc
        ),
        CountryDetails(
            "td",
            "+235",
            context.getString(R.string.chad),
            R.drawable.td
        ),
        CountryDetails(
            "tg",
            "+228",
            context.getString(R.string.togo),
            R.drawable.tg
        ),
        CountryDetails(
            "th",
            "+66",
            context.getString(R.string.thailand),
            R.drawable.th
        ),
        CountryDetails(
            "tj",
            "+992",
            context.getString(R.string.tajikistan),
            R.drawable.tj
        ),
        CountryDetails(
            "tk",
            "+690",
            context.getString(R.string.tokelau),
            R.drawable.tk
        ),
        CountryDetails(
            "tl",
            "+670",
            context.getString(R.string.timor_leste),
            R.drawable.tl
        ),
        CountryDetails(
            "tm",
            "+993",
            context.getString(R.string.turkmenistan),
            R.drawable.tm
        ),
        CountryDetails(
            "tn",
            "+216",
            context.getString(R.string.tunisia),
            R.drawable.tn
        ),
        CountryDetails(
            "to",
            "+676",
            context.getString(R.string.tonga),
            R.drawable.to
        ),
        CountryDetails(
            "tr",
            "+90",
            context.getString(R.string.turkey),
            R.drawable.tr
        ),
        CountryDetails(
            "tt",
            "+1",
            context.getString(R.string.trinidad_amp_tobago),
            R.drawable.tt
        ),
        CountryDetails(
            "tv",
            "+688",
            context.getString(R.string.tuvalu),
            R.drawable.tv
        ),
        CountryDetails(
            "tw",
            "+886",
            context.getString(R.string.taiwan),
            R.drawable.tw
        ),
        CountryDetails(
            "tz",
            "+255",
            context.getString(R.string.tanzania_united_republic_of),
            R.drawable.tz
        ),
        CountryDetails(
            "ua",
            "+380",
            context.getString(R.string.ukraine),
            R.drawable.ua
        ),
        CountryDetails(
            "ug",
            "+256",
            context.getString(R.string.uganda),
            R.drawable.ug
        ),
        CountryDetails(
            "us",
            "+1",
            context.getString(R.string.united_states),
            R.drawable.us
        ),
        CountryDetails(
            "uy",
            "+598",
            context.getString(R.string.uruguay),
            R.drawable.uy
        ),
        CountryDetails(
            "uz",
            "+998",
            context.getString(R.string.uzbekistan),
            R.drawable.uz
        ),
        CountryDetails(
            "va",
            "+379",
            context.getString(R.string.holy_see_vatican_city_state),
            R.drawable.va
        ),
        CountryDetails(
            "vc",
            "+1",
            context.getString(R.string.saint_vincent_amp_the_grenadines),
            R.drawable.vc
        ),
        CountryDetails(
            "ve",
            "+58",
            context.getString(R.string.venezuela_bolivarian_republic_of),
            R.drawable.ve
        ),
        CountryDetails(
            "vg",
            "+1",
            context.getString(R.string.british_virgin_islands),
            R.drawable.vg
        ),
        CountryDetails(
            "vi",
            "+1",
            context.getString(R.string.us_virgin_islands),
            R.drawable.vi
        ),
        CountryDetails(
            "vn",
            "+84",
            context.getString(R.string.vietnam),
            R.drawable.vn
        ),
        CountryDetails(
            "vu",
            "+678",
            context.getString(R.string.vanuatu),
            R.drawable.vu
        ),
        CountryDetails(
            "wf",
            "+681",
            context.getString(R.string.wallis_and_futuna),
            R.drawable.wf
        ),
        CountryDetails(
            "ws",
            "4685",
            context.getString(R.string.samoa),
            R.drawable.ws
        ),
        CountryDetails(
            "xk",
            "+383",
            context.getString(R.string.kosovo),
            R.drawable.xk
        ),
        CountryDetails(
            "ye",
            "+967",
            context.getString(R.string.yemen),
            R.drawable.ye
        ),
        CountryDetails(
            "yt",
            "+262",
            context.getString(R.string.mayotte),
            R.drawable.yt
        ),
        CountryDetails(
            "za",
            "+27",
            context.getString(R.string.south_africa),
            R.drawable.za
        ),
        CountryDetails(
            "zm",
            "+260",
            context.getString(R.string.zambia),
            R.drawable.zm
        ),
        CountryDetails(
            "zw",
            "+263",
            context.getString(R.string.zimbabwe),
            R.drawable.zw
        ),
    ).sortedBy { it.countryName }
}