package com.arpitkatiyarprojects.countrypickerproject.ui.country_picker_demo

import kotlinx.serialization.Serializable


@Serializable
object MainScreenDestination

@Serializable
object CountryPickerWithoutTextFieldDestination

@Serializable
object CountryPickerWithOutlinedTextFieldDestination